### ISSUE TITLE
-o return not a valid filename

### ISSUE THREAD

**Issue by twelvesummer** [hsinnan75/Kart#5]
hello, I run Kart in my server, but it returns :
```
Warning: [/data1/xxx/USER/xxxx/project/2.mapping/analyse/Kart/MTB0.sam] is not a valid filename!
```
I change filename with MTB0.sam, it runs. But I need to set abspath in my pipeline.

**Comment by hsinnan75** [comment]
Hi, thanks for using Kart. The sam output filename is not valid if it contains any characters which are not alphabets, digital or '.'
I used your filename to run Kart and it did not show the warning message. Please check again if xxxx contains any characters are not alphabets or digital. If they do (for example, '-'), please let me know and I can add them to valid character list.

**Comment by twelvesummer** [comment]
Thank you very much for your quick reply~I have updated the latest program and successfully completed the analysis.
